services:
  db:
    image: postgres:16-alpine
    container_name: docucore-db
    environment:
      POSTGRES_USER: docucore
      POSTGRES_PASSWORD: docucore
      POSTGRES_DB: docucore
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docucore"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
