import { expect, test } from './fixtures'

test.describe('CAL-01 calendario operativo', () => {
  test('navigates real calendar views and manages a manual event', async ({ page, consoleIssues }) => {
    const title = `Evento CAL E2E ${Date.now()}`
    await page.goto('/calendar')
    await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible()
    await expect(page).toHaveURL(/\/calendar\?view=month&date=2026-07-15/)
    await expect(page.getByText('ITV', { exact: true })).toBeVisible()

    await page.getByRole('button', { name: 'Periodo siguiente' }).click()
    await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Hoy' }).last()).toBeVisible()
    await page.getByRole('button', { name: 'Hoy' }).last().click()
    await expect(page).toHaveURL(/date=2026-07-15/)
    await page.getByRole('button', { name: 'Semana', exact: true }).click()
    await expect(page).toHaveURL(/view=week/)
    await page.getByRole('button', { name: 'Día', exact: true }).click()
    await expect(page).toHaveURL(/view=day/)
    await expect(page.getByText('No hay eventos para este día.')).toHaveCount(0)

    await page.getByRole('button', { name: 'Nuevo evento' }).click()
    const form = page.getByRole('dialog', { name: 'Nuevo evento' })
    await form.getByLabel('Título').fill(title)
    await form.getByLabel('Fecha').fill('2026-07-15')
    await form.getByLabel('Tipo').selectOption('review')
    await form.getByRole('button', { name: 'Crear evento' }).click()
    await expect(form).toBeHidden()
    await expect(page.getByRole('button', { name: title })).toBeVisible()

    await page.getByRole('button', { name: title }).click()
    const details = page.getByRole('dialog', { name: title })
    await expect(details.getByText('Hoy', { exact: true })).toBeVisible()
    await details.getByRole('button', { name: 'Editar' }).click()
    const edit = page.getByRole('dialog', { name: 'Editar evento' })
    await edit.getByLabel('Título').fill(`${title} actualizado`)
    await edit.getByRole('button', { name: 'Guardar cambios' }).click()
    await expect(edit).toBeHidden()
    await expect(page.getByRole('button', { name: `${title} actualizado` })).toBeVisible()

    await page.getByRole('button', { name: `${title} actualizado` }).click()
    const updatedDetails = page.getByRole('dialog', { name: `${title} actualizado` })
    await updatedDetails.getByRole('button', { name: 'Completar' }).click()
    await expect(updatedDetails.getByText('Completado', { exact: true })).toBeVisible()
    await updatedDetails.getByRole('button', { name: 'Eliminar' }).click()
    const confirm = page.getByRole('dialog', { name: 'Eliminar evento' })
    await confirm.getByRole('button', { name: 'Eliminar evento' }).click()
    await expect(page.getByRole('button', { name: `${title} actualizado` })).toHaveCount(0)
    expect(consoleIssues).toEqual([])
  })

  test('shows preventive progress and keeps incomplete execution non-completable', async ({ page, consoleIssues }) => {
    await page.goto('/calendar?view=day&date=2026-08-05')
    await expect(page.getByRole('heading', { name: 'Calendario', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Mantenimiento preventivo trimestral' }).click()
    const details = page.getByRole('dialog', { name: 'Mantenimiento preventivo trimestral' })
    await expect(details.getByText('0/3 tareas completadas')).toBeVisible()
    await expect(details.getByRole('button', { name: 'Completar' })).toHaveCount(0)
    await details.getByRole('button', { name: 'Abrir preventivo' }).click()
    await expect(page).toHaveURL(/\/assets\?assetId=/)
    const assetModal = page.getByRole('dialog', { name: 'Torno CNC Haas ST-20' })
    await expect(assetModal).toBeVisible()
    await expect(assetModal.getByText('Preventivos y planes periódicos')).toBeVisible()
    expect(consoleIssues).toEqual([])
  })
})
