import type { LucideIcon } from 'lucide-react'
import {
  AirVent, AlarmSmoke, Antenna, Archive, Atom, Axe, Battery, BatteryCharging, Beaker, BellRing, Biohazard, Bot, Box, BrushCleaning,
  Building2, BusFront, Cable, Camera, Car, CarFront, CircleAlert, CircleDot, CirclePower, CircuitBoard, CloudRain, Cog, Component,
  Container, Crosshair, Cpu, Cylinder, Dam, Database, Disc, DoorOpen, Drill, Drone, Droplet, Droplets, Factory, Fan, Filter,
  FireExtinguisher, Flame, Flashlight, FlaskConical, Forklift, Fuel, Gauge, GlassWater, Hammer, HardDrive, HardHat, Heater, House, KeyRound, Laptop,
  LifeBuoy, Magnet, Microscope, Monitor, MonitorCog, Motorbike, Network, Nut, Package, PackageCheck, PanelsTopLeft, PencilRuler,
  Pipette, Plane, Plug, PlugZap, Power, Printer, Radar, RadioTower, Refrigerator, RotateCw, Router, ScanBarcode, ScanLine,
  ScanQrCode, Server, ServerCog, Settings, Shield, ShieldAlert, ShieldCheck, Siren, Smartphone, Snowflake, SolarPanel, SquareStack,
  SatelliteDish, Scale, Syringe, Tablet, Tag, TestTube2, Thermometer, ThermometerSnowflake, ThermometerSun, Timer, ToolCase, Tractor, TrainFront,
  Truck, TruckElectric, Umbrella, Unplug, UtilityPole, Warehouse, Watch, Waves, Wifi, Wind, Workflow, Wrench, Zap,
} from 'lucide-react'
import { resolveAssetIconKey } from '@/lib/assetIconRegistry'
import type { AssetIconKey } from '../../shared/assetIconCatalog'

// Importaciones estáticas y explícitas: el catálogo está acotado y Vite puede
// tree-shakear todo Lucide fuera de esta selección industrial.
const iconComponents = {
  factory: Factory,
  cog: Cog,
  settings: Settings,
  wrench: Wrench,
  hammer: Hammer,
  drill: Drill,
  crane: Factory,
  conveyor: Workflow,
  container: Container,
  cylinder: Cylinder,
  disc: Disc,
  nut: Nut,
  'circle-power': CirclePower,
  'rotate-cw': RotateCw,
  fuel: Fuel,
  tank: Container,
  droplet: Droplet,
  waves: Waves,
  filter: Filter,
  gauge: Gauge,
  fan: Fan,
  wind: Wind,
  'air-vent': AirVent,
  heater: Heater,
  refrigerator: Refrigerator,
  snowflake: Snowflake,
  thermometer: Thermometer,
  'thermometer-sun': ThermometerSun,
  'thermometer-snowflake': ThermometerSnowflake,
  umbrella: Umbrella,
  axe: Axe,
  'brush-cleaning': BrushCleaning,
  'tool-case': ToolCase,
  ruler: PencilRuler,
  'pencil-ruler': PencilRuler,
  scale: Scale,
  magnet: Magnet,
  flashlight: Flashlight,
  zap: Zap,
  plug: Plug,
  'plug-zap': PlugZap,
  unplug: Unplug,
  battery: Battery,
  'battery-charging': BatteryCharging,
  'solar-panel': SolarPanel,
  'utility-pole': UtilityPole,
  cable: Cable,
  power: Power,
  flame: Flame,
  'fire-extinguisher': FireExtinguisher,
  'alarm-smoke': AlarmSmoke,
  siren: Siren,
  'bell-ring': BellRing,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'hard-hat': HardHat,
  'life-buoy': LifeBuoy,
  'circle-alert': CircleAlert,
  radar: Radar,
  antenna: Antenna,
  'satellite-dish': SatelliteDish,
  'radio-tower': RadioTower,
  'scan-line': ScanLine,
  'scan-barcode': ScanBarcode,
  'scan-qr-code': ScanQrCode,
  crosshair: Crosshair,
  timer: Timer,
  watch: Watch,
  microscope: Microscope,
  server: Server,
  'server-cog': ServerCog,
  database: Database,
  router: Router,
  network: Network,
  wifi: Wifi,
  monitor: Monitor,
  'monitor-cog': MonitorCog,
  laptop: Laptop,
  'hard-drive': HardDrive,
  printer: Printer,
  truck: Truck,
  'truck-electric': TruckElectric,
  forklift: Forklift,
  car: Car,
  'car-front': CarFront,
  motorbike: Motorbike,
  tractor: Tractor,
  'bus-front': BusFront,
  'train-front': TrainFront,
  plane: Plane,
  drone: Drone,
  warehouse: Warehouse,
  package: Package,
  'package-check': PackageCheck,
  box: Box,
  archive: Archive,
  'building-2': Building2,
  'factory-building': Factory,
  house: House,
  'door-open': DoorOpen,
  'panels-top-left': PanelsTopLeft,
  droplets: Droplets,
  'glass-water': GlassWater,
  dam: Dam,
  'cloud-rain': CloudRain,
  pipette: Pipette,
  'test-tube': TestTube2,
  'flask-conical': FlaskConical,
  beaker: Beaker,
  syringe: Syringe,
  biohazard: Biohazard,
  atom: Atom,
  cpu: Cpu,
  'circuit-board': CircuitBoard,
  camera: Camera,
  smartphone: Smartphone,
  tablet: Tablet,
  bot: Bot,
  'key-round': KeyRound,
  tag: Tag,
  'circle-dot': CircleDot,
  'square-stack': SquareStack,
  component: Component,
} satisfies Record<AssetIconKey, LucideIcon>

interface AssetIconProps {
  iconKey?: string | null
  className?: string
  size?: number
  strokeWidth?: number
  title?: string
}

export default function AssetIcon({ iconKey, className, size = 18, strokeWidth = 1.8, title }: AssetIconProps) {
  const resolvedKey = resolveAssetIconKey(iconKey)
  const Icon = iconComponents[resolvedKey]
  return <Icon aria-hidden={title ? undefined : true} aria-label={title} data-asset-icon={resolvedKey} className={className} size={size} strokeWidth={strokeWidth} />
}
