export interface AssetIconDefinition {
  key: string
  label: string
  group: string
}

// PLAN-04: catálogo finito y estable. Las claves son datos persistidos; los
// componentes SVG que las representan viven en AssetIcon.tsx.
export const assetIconDefinitions = [
  { key: 'factory', label: 'Fábrica', group: 'Maquinaria' },
  { key: 'cog', label: 'Engranaje', group: 'Maquinaria' },
  { key: 'settings', label: 'Ajustes mecánicos', group: 'Maquinaria' },
  { key: 'wrench', label: 'Llave inglesa', group: 'Maquinaria' },
  { key: 'hammer', label: 'Martillo', group: 'Maquinaria' },
  { key: 'drill', label: 'Taladro', group: 'Maquinaria' },
  { key: 'crane', label: 'Grúa', group: 'Maquinaria' },
  { key: 'conveyor', label: 'Cinta transportadora', group: 'Maquinaria' },
  { key: 'container', label: 'Contenedor industrial', group: 'Maquinaria' },
  { key: 'cylinder', label: 'Cilindro', group: 'Maquinaria' },
  { key: 'disc', label: 'Disco', group: 'Maquinaria' },
  { key: 'nut', label: 'Tuerca', group: 'Maquinaria' },
  { key: 'circle-power', label: 'Motor', group: 'Motores y bombas' },
  { key: 'rotate-cw', label: 'Rotación', group: 'Motores y bombas' },
  { key: 'fuel', label: 'Combustible', group: 'Motores y bombas' },
  { key: 'tank', label: 'Depósito', group: 'Motores y bombas' },
  { key: 'droplet', label: 'Bomba de líquido', group: 'Motores y bombas' },
  { key: 'waves', label: 'Flujo', group: 'Motores y bombas' },
  { key: 'filter', label: 'Filtro', group: 'Motores y bombas' },
  { key: 'gauge', label: 'Manómetro', group: 'Motores y bombas' },
  { key: 'fan', label: 'Ventilador', group: 'Ventilación y climatización' },
  { key: 'wind', label: 'Aire', group: 'Ventilación y climatización' },
  { key: 'air-vent', label: 'Rejilla de ventilación', group: 'Ventilación y climatización' },
  { key: 'heater', label: 'Calefactor', group: 'Ventilación y climatización' },
  { key: 'refrigerator', label: 'Refrigeración', group: 'Ventilación y climatización' },
  { key: 'snowflake', label: 'Frío', group: 'Ventilación y climatización' },
  { key: 'thermometer', label: 'Termómetro', group: 'Ventilación y climatización' },
  { key: 'thermometer-sun', label: 'Temperatura alta', group: 'Ventilación y climatización' },
  { key: 'thermometer-snowflake', label: 'Temperatura baja', group: 'Ventilación y climatización' },
  { key: 'umbrella', label: 'Protección climática', group: 'Ventilación y climatización' },
  { key: 'axe', label: 'Hacha', group: 'Herramientas' },
  { key: 'brush-cleaning', label: 'Limpieza', group: 'Herramientas' },
  { key: 'tool-case', label: 'Caja de herramientas', group: 'Herramientas' },
  { key: 'ruler', label: 'Regla', group: 'Herramientas' },
  { key: 'pencil-ruler', label: 'Diseño técnico', group: 'Herramientas' },
  { key: 'scale', label: 'Báscula', group: 'Herramientas' },
  { key: 'magnet', label: 'Imán', group: 'Herramientas' },
  { key: 'flashlight', label: 'Linterna', group: 'Herramientas' },
  { key: 'zap', label: 'Rayo eléctrico', group: 'Electricidad y energía' },
  { key: 'plug', label: 'Enchufe', group: 'Electricidad y energía' },
  { key: 'plug-zap', label: 'Conexión eléctrica', group: 'Electricidad y energía' },
  { key: 'unplug', label: 'Desconectado', group: 'Electricidad y energía' },
  { key: 'battery', label: 'Batería', group: 'Electricidad y energía' },
  { key: 'battery-charging', label: 'Batería cargando', group: 'Electricidad y energía' },
  { key: 'solar-panel', label: 'Panel solar', group: 'Electricidad y energía' },
  { key: 'utility-pole', label: 'Poste eléctrico', group: 'Electricidad y energía' },
  { key: 'cable', label: 'Cable', group: 'Electricidad y energía' },
  { key: 'power', label: 'Energía', group: 'Electricidad y energía' },
  { key: 'flame', label: 'Llama', group: 'Incendios y seguridad' },
  { key: 'fire-extinguisher', label: 'Extintor', group: 'Incendios y seguridad' },
  { key: 'alarm-smoke', label: 'Alarma de humo', group: 'Incendios y seguridad' },
  { key: 'siren', label: 'Sirena', group: 'Incendios y seguridad' },
  { key: 'bell-ring', label: 'Aviso', group: 'Incendios y seguridad' },
  { key: 'shield', label: 'Escudo', group: 'Incendios y seguridad' },
  { key: 'shield-check', label: 'Seguridad validada', group: 'Incendios y seguridad' },
  { key: 'shield-alert', label: 'Alerta de seguridad', group: 'Incendios y seguridad' },
  { key: 'hard-hat', label: 'Casco', group: 'Incendios y seguridad' },
  { key: 'life-buoy', label: 'Salvavidas', group: 'Incendios y seguridad' },
  { key: 'circle-alert', label: 'Alerta', group: 'Incendios y seguridad' },
  { key: 'radar', label: 'Radar', group: 'Sensores e instrumentación' },
  { key: 'antenna', label: 'Antena', group: 'Sensores e instrumentación' },
  { key: 'satellite-dish', label: 'Antena parabólica', group: 'Sensores e instrumentación' },
  { key: 'radio-tower', label: 'Torre de radio', group: 'Sensores e instrumentación' },
  { key: 'scan-line', label: 'Escáner', group: 'Sensores e instrumentación' },
  { key: 'scan-barcode', label: 'Código de barras', group: 'Sensores e instrumentación' },
  { key: 'scan-qr-code', label: 'Código QR', group: 'Sensores e instrumentación' },
  { key: 'crosshair', label: 'Punto de medida', group: 'Sensores e instrumentación' },
  { key: 'timer', label: 'Temporizador', group: 'Sensores e instrumentación' },
  { key: 'watch', label: 'Reloj', group: 'Sensores e instrumentación' },
  { key: 'microscope', label: 'Microscopio', group: 'Sensores e instrumentación' },
  { key: 'server', label: 'Servidor', group: 'Servidores y redes' },
  { key: 'server-cog', label: 'Servidor gestionado', group: 'Servidores y redes' },
  { key: 'database', label: 'Base de datos', group: 'Servidores y redes' },
  { key: 'router', label: 'Router', group: 'Servidores y redes' },
  { key: 'network', label: 'Red', group: 'Servidores y redes' },
  { key: 'wifi', label: 'Wifi', group: 'Servidores y redes' },
  { key: 'monitor', label: 'Monitor', group: 'Servidores y redes' },
  { key: 'monitor-cog', label: 'Consola', group: 'Servidores y redes' },
  { key: 'laptop', label: 'Portátil', group: 'Servidores y redes' },
  { key: 'hard-drive', label: 'Disco', group: 'Servidores y redes' },
  { key: 'printer', label: 'Impresora', group: 'Servidores y redes' },
  { key: 'truck', label: 'Camión', group: 'Vehículos' },
  { key: 'truck-electric', label: 'Camión eléctrico', group: 'Vehículos' },
  { key: 'forklift', label: 'Carretilla elevadora', group: 'Vehículos' },
  { key: 'car', label: 'Coche', group: 'Vehículos' },
  { key: 'car-front', label: 'Coche frontal', group: 'Vehículos' },
  { key: 'motorbike', label: 'Moto', group: 'Vehículos' },
  { key: 'tractor', label: 'Tractor', group: 'Vehículos' },
  { key: 'bus-front', label: 'Autobús', group: 'Vehículos' },
  { key: 'train-front', label: 'Tren', group: 'Vehículos' },
  { key: 'plane', label: 'Avión', group: 'Vehículos' },
  { key: 'drone', label: 'Dron', group: 'Vehículos' },
  { key: 'warehouse', label: 'Almacén', group: 'Almacenamiento y edificios' },
  { key: 'package', label: 'Paquete', group: 'Almacenamiento y edificios' },
  { key: 'package-check', label: 'Paquete verificado', group: 'Almacenamiento y edificios' },
  { key: 'box', label: 'Caja', group: 'Almacenamiento y edificios' },
  { key: 'archive', label: 'Archivo', group: 'Almacenamiento y edificios' },
  { key: 'building-2', label: 'Edificio', group: 'Almacenamiento y edificios' },
  { key: 'factory-building', label: 'Nave industrial', group: 'Almacenamiento y edificios' },
  { key: 'house', label: 'Edificio auxiliar', group: 'Almacenamiento y edificios' },
  { key: 'door-open', label: 'Puerta', group: 'Almacenamiento y edificios' },
  { key: 'panels-top-left', label: 'Panel', group: 'Almacenamiento y edificios' },
  { key: 'droplets', label: 'Agua', group: 'Agua y laboratorio' },
  { key: 'glass-water', label: 'Vaso de agua', group: 'Agua y laboratorio' },
  { key: 'dam', label: 'Presa', group: 'Agua y laboratorio' },
  { key: 'cloud-rain', label: 'Lluvia', group: 'Agua y laboratorio' },
  { key: 'pipette', label: 'Pipeta', group: 'Agua y laboratorio' },
  { key: 'test-tube', label: 'Tubo de ensayo', group: 'Agua y laboratorio' },
  { key: 'flask-conical', label: 'Matraz', group: 'Agua y laboratorio' },
  { key: 'beaker', label: 'Vaso de laboratorio', group: 'Agua y laboratorio' },
  { key: 'syringe', label: 'Jeringa', group: 'Agua y laboratorio' },
  { key: 'biohazard', label: 'Riesgo biológico', group: 'Agua y laboratorio' },
  { key: 'atom', label: 'Átomo', group: 'Agua y laboratorio' },
  { key: 'cpu', label: 'Procesador', group: 'Dispositivos y genéricos' },
  { key: 'circuit-board', label: 'Placa electrónica', group: 'Dispositivos y genéricos' },
  { key: 'camera', label: 'Cámara', group: 'Dispositivos y genéricos' },
  { key: 'smartphone', label: 'Teléfono', group: 'Dispositivos y genéricos' },
  { key: 'tablet', label: 'Tableta', group: 'Dispositivos y genéricos' },
  { key: 'bot', label: 'Robot', group: 'Dispositivos y genéricos' },
  { key: 'key-round', label: 'Llave', group: 'Dispositivos y genéricos' },
  { key: 'tag', label: 'Etiqueta', group: 'Dispositivos y genéricos' },
  { key: 'circle-dot', label: 'Genérico', group: 'Dispositivos y genéricos' },
  { key: 'square-stack', label: 'Conjunto', group: 'Dispositivos y genéricos' },
  { key: 'component', label: 'Componente', group: 'Dispositivos y genéricos' },
] as const satisfies readonly AssetIconDefinition[]

export type AssetIconKey = typeof assetIconDefinitions[number]['key']
export const DEFAULT_ASSET_ICON_KEY: AssetIconKey = 'package'
export const assetIconKeys = assetIconDefinitions.map((definition) => definition.key) as AssetIconKey[]

export function isAssetIconKey(value: unknown): value is AssetIconKey {
  return typeof value === 'string' && assetIconKeys.includes(value as AssetIconKey)
}
